### ISSUE TITLE
Doubt in the code

### ISSUE THREAD

**Issue by Josemi13** [FrancescoLR/Bones-segmentation-in-CT-scans#1]
Hi,

I would like to use your u-net. I've some doubts relating of the code:

![image](https://user-images.githubusercontent.com/67199155/118359947-ddb77e00-b585-11eb-816e-dbdd9bf07890.png)

- Why do you put 4x512x512 or 8x512x512 in the lines of the code?

![image](https://user-images.githubusercontent.com/67199155/118360121-85cd4700-b586-11eb-9c6c-a1118c028947.png)

- The number 7 that you do reference as parameter during the code, Is the number of typos of bones?

Best,

Josemi

**Comment by FrancescoLR** [comment]
Hi Josemi, thanks for your interest!

- 4 or 8 here it's the batch size. Feel free to modify it of course, but make sure to change it as well in the generator function.
- Correct, there are 6 different bone types plus the background.

Let me know if you encounter any other issues running the code.

Cheers,
Francesco

**Comment by Josemi13** [comment]
HI, 

Thanks for you comment. 

I only have two labels: bone and background so I will try to adapt for this case. If you recommend me something to do, I would be so grateful.

The images of my dataset are CT Scans in .png format. Could I introduce the images and masks in this format? or I have to change to other.

Best,

Josemi

**Comment by FrancescoLR** [comment]
Yes, in this case, you should adapt it setting the n of classes to 2 instead of 7. 

Regarding the image format, you should change the sitk.ReadImage function (which reads nifty) to another one which reads png (for example imageio.imread). Then, once you have loaded the images as numpy arrays, everything else remains the same.

**Comment by Josemi13** [comment]
Hi,

I'm using python 2.7.12 and I think imageio doesn't work it. Do you know other library?

Thanks for your help.

Josemi

**Comment by FrancescoLR** [comment]
You could try with matplotlib.image then (https://matplotlib.org/2.0.0/users/image_tutorial.html). Not sure it will work with Python 2.7 though.

**Comment by Josemi13** [comment]
Thanks for the link. 

![image](https://user-images.githubusercontent.com/67199155/118372983-93012a80-b5b4-11eb-9cfa-afdab641cee5.png)

Why do you put unet1.h5? I only have unet.h5.

Thanks for your time. I' m so grateful. 

Best,

Josemi

**Comment by FrancescoLR** [comment]
My mistake sorry, it should be unet.h5 . I have now corrected it.

**Comment by Josemi13** [comment]
HI,

![image](https://user-images.githubusercontent.com/67199155/118376925-2f362c00-b5cb-11eb-93d9-2330fe78bedc.png)

Where should I load the path of the folders for images and masks?

Thanks so much.

Best,

Josemi

**Comment by FrancescoLR** [comment]
Here image_path should point to the main directory where the images/masks are.
Hope this helps.

**Comment by Josemi13** [comment]
HI, 

I have some doubts about the different folders used:
- Folder for the images in the training (Original 2D images) in function generator2()
- Folder for the masks in the training ( Final Mask 2D) in function generator2()
- Folder for original images to validate in generator_val() . I think that I have to load different images that I use it  in the training. Is it correct?
- Folder for masks (relating to the images of the validation folder) in in generator_val().

Where should I load the images they are input to test the u-net?

If I have an idea wrong, correct me please.

Thanks for  your comments.

Best,

Josemi

**Comment by FrancescoLR** [comment]
Hi Josemi,
That is correct. There are three different folders, one for training, one for validation, and one for testing. If you are only testing the pre-trained unet, you can go directly to the last cells of the notebook. Where it says 
"#Load scan converted to a numpy array " you should load your testing scan and convert it to a numpy array. The few next cells will apply the model and generate the output.

**Comment by Josemi13** [comment]
HI,

I have 280 images to train, 65 images to validate and 70 images to test. 

![image](https://user-images.githubusercontent.com/67199155/118398372-9221d480-b658-11eb-9fde-c643691121bf.png)

Is that your training images? 

I don't understand the next operation:

![image](https://user-images.githubusercontent.com/67199155/118398421-d319e900-b658-11eb-8755-ec894eae814e.png)

Which is the value of "number of sample" and "batch size"?

Other question:

![image](https://user-images.githubusercontent.com/67199155/118410255-cf08be00-b68e-11eb-9368-9855e5d0e3e6.png)

I have the doubt if E1.npy only loads a image or the full set of a CT Scan. The comment  says "scan" and it should be a CT Scans (set of images) or unique image to segment.

In case of a full CT Scans, the file E1.npy is a script where the output should be a numpy array for each image or it should be a array to all the set of the images.  

Thanks for your time. 

Best,

Josemi

**Comment by FrancescoLR** [comment]
Hi Josemi,
Number of sample is the number of 2D images I have for training. The batch size can be set to either 4 or 8.

Regarding your second question, that's correct, E1.npy is a numpy array with a full CT scan, so a complete set of 2D images.
Hope this helps.

**Comment by Josemi13** [comment]
HI,

Relating of your comment, Should I add the images to the numpy array as a new row or column? 

In my case, the numpy array is called file_npy:

![image](https://user-images.githubusercontent.com/67199155/118416836-d4c3cb00-b6b1-11eb-8dcd-1117cab33aa1.png)

Thanks for your help.

Josemi

**Comment by Josemi13** [comment]
[report_Error.txt](https://github.com/FrancescoLR/Bones-segmentation-in-CT-scans/files/6496088/report_Error.txt)


[train_and_test.zip](https://github.com/FrancescoLR/Bones-segmentation-in-CT-scans/files/6503120/train_and_test.zip)

HI,

Relating of your comment, should I add a new image to the numpy array as row or column? 

In my case, the numpy array is called file_npy:
![image](https://user-images.githubusercontent.com/67199155/118416952-4ef44f80-b6b2-11eb-9081-5fe93770a9a5.png)


I have executed training_and_predict():

**ValueError: Dimensions must be equal, but are 2 and 7 for 'mul_1' (op: 'Mul') with input shapes: [2097152,2], [2097152,7].**

- For only 2 labels, I have modified in get_unet():
![image](https://user-images.githubusercontent.com/67199155/118538469-857fa800-b74e-11eb-8500-50da27300d85.png)

conv10 = Conv2D(**2**, (1, 1), activation='linear')(act9)
flat = Reshape((img_rows*img_cols,**2**))(conv10)

The rest of the code in the method is same like your project.

- In train_and_predict():
![image](https://user-images.githubusercontent.com/67199155/118538641-c11a7200-b74e-11eb-852c-ac6e45ff5d89.png)

steps_per_epoch=**47**  # I have 280 images and batch_size = 8
val_steps=**32** #value standard

 model.fit_generator(generator2("../Train/Image/","../Train/Mask"**,2**), steps_per_epoch=steps_per_epoch, epochs=100, max_q_size=4, verbose=1, initial_epoch=0, callbacks=[model_checkpoint,history, history_loss, AdamLearningRateTracker()])

Could you give an idea about the error? I send you the code modified to 2 labels. 

Thanks for your help.

Best,

Josemi

**Comment by Josemi13** [comment]
HI,

Relating of your comment, should I add a new image to the numpy array as row or column? 

In my case, the numpy array is called file_npy:
![image](https://user-images.githubusercontent.com/67199155/118416952-4ef44f80-b6b2-11eb-9081-5fe93770a9a5.png)


I have executed training_and_predict():

![image](https://user-images.githubusercontent.com/67199155/118890654-59efef80-b8ff-11eb-9692-685cdbf446fd.png)

The function generator2():

![image](https://user-images.githubusercontent.com/67199155/118890725-7be97200-b8ff-11eb-82e4-5847cb0a8265.png)

I have run with data augmented and without it, and the error appears.

The training:

![image](https://user-images.githubusercontent.com/67199155/118891827-3d07ec00-b900-11eb-8227-9da51eb4ca71.png)

Could you give an idea about the error? 

Thanks for your help.

Best,

Josemi

**Comment by FrancescoLR** [comment]
Hi Josemi,
you should check the shape of your numpy array. It looks like is (512,512,3) instead of (512,512,1).

**Comment by FrancescoLR** [comment]
Feel free to drop me an email in case of further questions: francesco.larosa@epfl.ch
