### ISSUE TITLE
Can't Find Data Folder 

### ISSUE THREAD

**Issue by SoheilDavoudi98** [FrancescoLR/Bones-segmentation-in-CT-scans#2]
HI Sir
I hope you have a nice day.
I am a student and I want to check your code for my project.
but I cant find "Data folder" in files you uploaded in repository
I would appreciate you very much if you send me some data or just tell me what is the format of the data to be tested in neural net.

**Comment by FrancescoLR** [comment]
Hello,
unfortunately, I was not allowed to share the data. My data was in the format .mhd, but any format is fine as long as you modify the following lines of code where the dataset is loaded:

            image_name="O_" +str(index)+ ".mhd" #check name!
            mask_name="M_" +str(index)+ ".mhd" #check name!
     
            img= sitk.ReadImage(os.path.join(image_path, image_name),sitk.sitkInt16)
            img = sitk.GetArrayFromImage(img)
            mas= sitk.ReadImage(os.path.join(mask_path, mask_name),sitk.sitkInt16)
            mas = sitk.GetArrayFromImage(mas)

Hope this helps.

Cheers,
Francesco

**Comment by SoheilDavoudi98** [comment]
I have to replace "image_t = model.predict(t, batch_size=6, verbose=1)" t with mas?

image_t = model.predict(mas, batch_size=6, verbose=1) ?

**Comment by SoheilDavoudi98** [comment]
what is img and mas?

**Comment by SoheilDavoudi98** [comment]
can you please send me a just one mhd file that is public?

**Comment by FrancescoLR** [comment]
For the testing, t should be a numpy array (.npy) as specified in the comments. You should load it beforehand and convert it to a numpy array. 

A public available dataset can be found here: https://www.nih.gov/news-events/news-releases/nih-clinical-center-releases-dataset-32000-ct-images Files are not in the .mdh format, but as long as you load and convert them to numpy arrays this is perfectly fine for my network.

**Comment by SoheilDavoudi98** [comment]
I dont understand  what should i give img_path and mask_path in generator function

I have one png file

**Comment by FrancescoLR** [comment]
The two paths are needed for training. In this case, you need an entire dataset, not a single image. If you have a single png file you should simply test the trained model on your image, you can ignore the training part of the code.
Hope this helps.

**Comment by SoheilDavoudi98** [comment]
t= np.load('../Data/E1.npy')
does E1.npy needed to have any specific dimension?
cause for example my picture have 500*500*3 dimension

**Comment by FrancescoLR** [comment]
Yes, please reshape it to 512x512 before feeding it to the network.

**Comment by SoheilDavoudi98** [comment]
I'm sorry for asking too questions but what about the third dimension?

is it ok that final array has shape (512,512,3)?

**Comment by FrancescoLR** [comment]
The third dimension should be 1 (gray intensity values). Please make sure to convert the RGB image (512,512,3) to grayscale (512,512,1).

**Comment by SoheilDavoudi98** [comment]
ValueError: Input 0 of layer "model_2" is incompatible with the layer: expected shape=(None, 512, 512, 1), found shape=(None, 512, 1, 1)

import cv2
t = cv2.imread("/content/test2.png",0)
t = np.reshape(t,(512,512,1))
t = np.expand_dims(t, axis=3)
image_t = model.predict(t, batch_size=6, verbose=1)

error in running this code

**Comment by FrancescoLR** [comment]
Check the dims of t before model.predict. As I told you, it should have dim (512,512,1), but here it seems that it is (512,1,1).

**Comment by SoheilDavoudi98** [comment]
it is (512,512,1)

**Comment by SoheilDavoudi98** [comment]
after excecuting t = np.expand_dims(t, axis=3) it will become (512,512,1,1)

**Comment by FrancescoLR** [comment]
Ah okay, please remove this line then!

**Comment by FrancescoLR** [comment]
The input should be (512,512,1)

**Comment by SoheilDavoudi98** [comment]
import cv2
t = cv2.imread("/content/test2.png",0)
t = np.reshape(t,(512,512,1))
print(t.shape)
image_t = model.predict(t, batch_size=6, verbose=1)


(512, 512, 1)
WARNING:tensorflow:Model was constructed with shape (None, 512, 512, 1) for input KerasTensor(type_spec=TensorSpec(shape=(None, 512, 512, 1), dtype=tf.float32, name='input_4'), name='input_4', description="created by layer 'input_4'"), but it was called on an input with incompatible shape (None, 512, 1, 1).
---------------------------------------------------------------------------


:((((((((((((((((((((((((((((((((((((((((((((((((((((((((

**Comment by SoheilDavoudi98** [comment]
ValueError: Exception encountered when calling layer "max_pooling2d_12" (type MaxPooling2D).
    
    Negative dimension size caused by subtracting 2 from 1 for '{{node model_3/max_pooling2d_12/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 2, 2, 1], padding="VALID", strides=[1, 2, 2, 1]](model_3/activation_58/Relu)' with input shapes: [?,512,1,16].
    
    Call arguments received:
      • inputs=tf.Tensor(shape=(None, 512, 1, 16), dtype=float32)

**Comment by FrancescoLR** [comment]
Strange, I do not understand why your input is still (512,1,1)... Can you try doing: t = np.reshape(t,(1,512,512,1)) ?

**Comment by SoheilDavoudi98** [comment]
it becomes ok

after that how can i see the converted images?

**Comment by FrancescoLR** [comment]
Great. You save the prediction:
image_t=np.reshape(image_t,(512,512,7))
spine=image_t[:,:,2] #select class
np.save('../Test/spine.npy', spine)

instead of 2, write 3 for the hips, 4 for the sternum, 5 for the ribs, 6 for the sacrum, and 7 for the femur.
To see the images you can open them with any visualization software, but a format conversion might be needed.

**Comment by FrancescoLR** [comment]
I suggest you overlay the mask over the original image to assess the segmentation.

**Comment by SoheilDavoudi98** [comment]
hi again

I tried so much but all of my outputs are black pictures

can you help me?

**Comment by FrancescoLR** [comment]
Can you tell me which values these arrays have? You should have a probability map, where the value of each pixel is between 0 and 1.

**Comment by SoheilDavoudi98** [comment]
yes, they are between 0 and 1

must map it to 0 to 255?

**Comment by FrancescoLR** [comment]
No, you should set a threshold, let's say 0.9 (this value should be optimised on your data), and map them to either 0 or 1. 1 will show you the relative class you selected and 0 will be the background. In my thesis all of this is well explained: https://amslaurea.unibo.it/14561/1/A%20deep%20learning%20approach%20to%20bone%20segmentation%20in%20CT%20scans.pdf (from page 50 or so).
Hope it helps.

**Comment by FrancescoLR** [comment]
I'll close the issue now, feel free to open a new one if you have other errors.
